name: "Generate JSON array"
description: "Generate JSON array of length"
author: Vladimir Levin
branding:
  icon: code
  color: purple
inputs:
  length:
    description: Array length
    required: true
  template:
    description: 'By default array values are indexes, can be customized with template. Example: "item-{{index}}"'
  startIndex:
    description: "What should be first index (default: 0)"
    default: '0'
  positiveOnly:
    description: "Return only positive values"
    default: 'false'
  negativeOnly:
    description: "Return only negative values"
    default: 'false'
  to_file:
    description: Save result to file
    default: 'false'
outputs:
  result:
    description: Result array
runs:
  using: 'node20'
  main: 'action/index.js'
